config/routes.rb
Rails.application.routes.draw do

  get 'field_subscriptions/create'

  get 'field_subscriptions/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :forum_admins, only:[:create, :destroy, :index, :new]

  resources :banned_users, only:[:create, :destroy, :index, :new]

  resources :closed_posts, only:[:create, :destroy, :index, :new]

  get 'results' => 'search#show'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'

  get 'forums' => 'topics#index'

  get 'landing' => 'static_pages#landing'

  resources :users do
    get 'questions' => 'users#questions'
  end

  resources :account_activations, only: [:edit]

  resources :notifications, only:[:index, :destroy]

  resources :moderators, only:[:create, :destroy, :index, :new]

  get 'admin_functions' => 'static_pages#admin_functions'

  resources :closings, only:[:create, :new]

  resources :replies, only:[:create, :delete]

  resources :posts, only:[:destroy, :create]

  resources :fields, only:[ :create, :new, :destroy ,:index]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'question_vote' => 'questions_votes#vote'
  get 'answer_vote' => 'answer_votes#vote'
  get 'best_answer' =>'answers#best'
  get 'signup' => 'users#new'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout'=> 'session#destroy'

  resources :answers, only:[:create]

  resources :questions, only:[:new, :destroy, :create, :index]

  resources :topics do
    resources :posts
  end

  resources :fields, path: '' , only:[:show]  do
    resources :questions, only:[:show, :edit, :new]
    get 'questions' => 'fields#questions'
    get 'new-moderator' => 'fields#new_moderator'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :answer_votes, dependent: :delete_all

  before_destroy


  def destroy_notification
    Notification.where(model_id:id, desc:"best_answer").destroy_all
    Notification.where(model_id:id, desc:"new_answer").destroy_all
  end
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
end

app/models/banned_user.rb
class BannedUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/closed_post.rb
class ClosedPost < ActiveRecord::Base
  belongs_to :forum_admin
  belongs_to :post
end

app/models/closing.rb
class Closing < ActiveRecord::Base
  belongs_to :moderator
  belongs_to :question
  validates :reason, presence: true
end

app/models/field.rb
class Field < ActiveRecord::Base
  has_many :questions, dependent: :delete_all
end

app/models/forum_admin.rb
class ForumAdmin < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
  belongs_to :user
  belongs_to :field
  validates :user,  presence: true
  validates :field,  presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  default_scope	->	{	order(created_at:	:desc)	}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope	->	{	order(created_at:	:desc)	}
  has_many :answers, :dependent => :delete_all
  has_many :question_votes , :dependent => :delete_all
end

app/models/question_vote.rb
class QuestionVote < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  has_secure_password
  has_many :questions, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  mount_uploader :avatar, AvatarUploader
  validate :avatar_size
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,	presence:	true,	length:	{	maximum:	255	}, format:	{	with:	VALID_EMAIL_REGEX	}, uniqueness:	{	case_sensitive:	false	}
  validates :name, presence: true, format: {with: /\A[a-zA-Z0-9]+\Z/}


  def authenticate?(password)
    BCrypt::Password(:password_digest).is_password?(password_digest)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def admin?
    if admin
      true
    end
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def notifications_count
    size = Notification.where(user_id: self.id, seen: nil).size
  end

  private

  # Validates the size of an uploaded picture.
  def avatar_size
    if avatar.size > 5.megabytes
      errors.add(:avatar, "should be less than 5MB")
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :logged_in, except: [:show, :index]
  def new
    if current_user.admin?
      @topic = Topic.new
    else
      flash[:danger] = "Not authorized"
      redirect_to root_url
    end
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.url = check_duplicate_url @topic.name.split(" ").join("_")[0..30], Topic
    @topic.save
    flash.now[:success] = "Topic created"
    redirect_to forums_path
  end

  def show
    @topic = Topic.find_by(url: params[:id])
    @posts = Post.where(topic_id: @topic.id)
  end

  def destroy
  end

  def index
    @topics =Topic.all
  end

  private
  def topic_params
    params.require(:topic).permit(:general, :name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  @@counter = 0
  def check_duplicate_url(url)
    if !Topic.find_by(url: url).nil?
      @@counter = @@counter.to_i + 1
      if @@counter != 0
        places = (Math.log10 @@counter).to_int
      end

      if !@@counter.nil?
        url[-url.size..-(places+1)] = @@counter.to_s
      end
      @new_url = check_duplicate_url (url)
    else
      url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/_topic.html.erb
<a href="#" class="topic-link no-formatt"><div><%= topic.name %> <span class="posts">Posts:<%= Post.where(topic: topic).size %></span></div></a>

app/views/topics/index.html.erb
<% provide :title, 'List of Forums' %>
<div class="topics-container">

  <table class="topics-table">
	<thead>
	<tr>
	  <th class="topic-general" colspan="2">
		General Topics
	  </th>
	</tr>
	</thead>
	<tbody>
	<% @topics.each do |topic| %>
		<% if topic.general? %>
			<tr><td><%= link_to topic.name, topic_path(topic.url), class: " no-formatt blue-link" %><span class="float-right not-important"> Posts:<%= Post.where(topic: topic).size %></td></tr>
		<% end %>
	<% end %>
	</tbody>
  </table>

  <table class="topics-table">
	<thead>
	<tr>
	  <th class="topic-general" colspan="2">
		Miscellaneous
	  </th>
	</tr>
	</thead>
	<tbody>
	<% @topics.each do |topic| %>
		<% if !topic.general? %>
			<tr><td><%= link_to topic.name, topic_path(topic.url), class: "no-formatt blue-link" %></td><td class="not-important"> Posts:<%= Post.where(topic: topic).size %></td></tr>
		<% end %>
	<% end %>
	</tbody>
  </table>

</div>

app/views/topics/new.html.erb
<% provide :title, 'New Topic' %>
<h1 class="page-title">
  New Forum Topic
</h1>
<%= form_for @topic, class: "form" do |f| %>
	<%= f.label :name, class:"form-label" %>
	<%= f.text_field :name, class:"form-input" %>
	<%= f.label :general, class:"form-label" %>
	<%= f.check_box :general, class:"form-input check-box" %>
	<%= f.submit "Submit", class:"btn" %>
<% end %>

app/views/topics/show.html.erb
<% provide :title, @topic.name.camelcase %>
<div class="breadcrunbs">
  <% if @topic.general? %>
	  <span class="breadcrumb"><%= link_to "General->", topics_path, class: "no-formatt blue-link small" %></span>
  <% else %>
	  <span class="breadcrumb"><%= link_to "Miscelleneous->", topics_path, class: "no-formatt blue-link small" %></span>
  <% end %>
  <span class="breadcrumb"><%= link_to @topic.name, topic_path(@topic.url), class: "no-formatt blue-link small" %></span>
</div>
<div style="overflow: initial;" class="float-right not-important"><%= link_to "+new post...", new_topic_post_path(topic_id: @topic.url), class:"btn-grey no-formatt not-important  "%></div>
<div class="topics-container">
  <table class="topics-table">
	<thead>
	<tr>
	  <th class="topic-general" colspan="2">
		<%= @topic.name %>
	  </th>
	</tr>
	</thead>
	<tbody>
	<% @posts.each do |post| %>
		<tr><td><%= link_to post.title, topic_post_path(id: post.url, topic_id: @topic.url) ,class: "no-formatt blue-link" %><span class="float-right not-important">Views:<%= %> &nbsp; Replies:<%= Reply.where(post_id: post.id).size %> &nbsp;by&nbsp; <%= link_to User.find(post.user_id).name, "#", class:"blue-link no-formatt" %></span></td></tr>
	<% end %>
	</tbody>
  </table>
</div>