config/routes.rb
Rails.application.routes.draw do

  get 'field_subscriptions/create'

  get 'field_subscriptions/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :forum_admins, only:[:create, :destroy, :index, :new]

  resources :banned_users, only:[:create, :destroy, :index, :new]

  resources :closed_posts, only:[:create, :destroy, :index, :new]

  get 'results' => 'search#show'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'

  get 'forums' => 'topics#index'

  get 'landing' => 'static_pages#landing'

  resources :users do
    get 'questions' => 'users#questions'
  end

  resources :account_activations, only: [:edit]

  resources :notifications, only:[:index, :destroy]

  resources :moderators, only:[:create, :destroy, :index, :new]

  get 'admin_functions' => 'static_pages#admin_functions'

  resources :closings, only:[:create, :new]

  resources :replies, only:[:create, :delete]

  resources :posts, only:[:destroy, :create]

  resources :fields, only:[ :create, :new, :destroy ,:index]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'question_vote' => 'questions_votes#vote'
  get 'answer_vote' => 'answer_votes#vote'
  get 'best_answer' =>'answers#best'
  get 'signup' => 'users#new'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout'=> 'session#destroy'

  resources :answers, only:[:create]

  resources :questions, only:[:new, :destroy, :create, :index]

  resources :topics do
    resources :posts
  end

  resources :fields, path: '' , only:[:show]  do
    resources :questions, only:[:show, :edit, :new]
    get 'questions' => 'fields#questions'
    get 'new-moderator' => 'fields#new_moderator'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :answer_votes, dependent: :delete_all

  before_destroy


  def destroy_notification
    Notification.where(model_id:id, desc:"best_answer").destroy_all
    Notification.where(model_id:id, desc:"new_answer").destroy_all
  end
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
end

app/models/banned_user.rb
class BannedUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/closed_post.rb
class ClosedPost < ActiveRecord::Base
  belongs_to :forum_admin
  belongs_to :post
end

app/models/closing.rb
class Closing < ActiveRecord::Base
  belongs_to :moderator
  belongs_to :question
  validates :reason, presence: true
end

app/models/field.rb
class Field < ActiveRecord::Base
  has_many :questions, dependent: :delete_all
end

app/models/forum_admin.rb
class ForumAdmin < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
  belongs_to :user
  belongs_to :field
  validates :user,  presence: true
  validates :field,  presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  default_scope	->	{	order(created_at:	:desc)	}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope	->	{	order(created_at:	:desc)	}
  has_many :answers, :dependent => :delete_all
  has_many :question_votes , :dependent => :delete_all
end

app/models/question_vote.rb
class QuestionVote < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  has_secure_password
  has_many :questions, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  mount_uploader :avatar, AvatarUploader
  validate :avatar_size
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,	presence:	true,	length:	{	maximum:	255	}, format:	{	with:	VALID_EMAIL_REGEX	}, uniqueness:	{	case_sensitive:	false	}
  validates :name, presence: true, format: {with: /\A[a-zA-Z0-9]+\Z/}


  def authenticate?(password)
    BCrypt::Password(:password_digest).is_password?(password_digest)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def admin?
    if admin
      true
    end
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def notifications_count
    size = Notification.where(user_id: self.id, seen: nil).size
  end

  private

  # Validates the size of an uploaded picture.
  def avatar_size
    if avatar.size > 5.megabytes
      errors.add(:avatar, "should be less than 5MB")
    end
  end

  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @unseen_notifications = Notification.where(user_id:  current_user.id, seen: nil)
    @seen_notifications = Notification.where(user_id:  current_user.id, seen: true)
  end

  def destroy
    Notification.find(params[:id]).destroy
    redirect_to notifications_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  @@counter = 0
  def check_duplicate_url(url)
    if !Topic.find_by(url: url).nil?
      @@counter = @@counter.to_i + 1
      if @@counter != 0
        places = (Math.log10 @@counter).to_int
      end

      if !@@counter.nil?
        url[-url.size..-(places+1)] = @@counter.to_s
      end
      @new_url = check_duplicate_url (url)
    else
      url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notifications/index.html.erb
<% provide :title, "Notifications" %>
<div class="page-title">Notifications</div>
<% @unseen_notifications.each  do |notification|%>
	<div class="notification unseen">

	  <div class="notification-content">
		<% if notification.desc=="new_answer"%>
			<% answer = Answer.find(notification.model_id) %>
			<% user = User.find(answer.user_id) %>
			<% question = Question.find(answer.question_id) %>
			<%= link_to user.name, user_path(user.name, class: "no-formatt blue-link") %> has answered your question "<%= link_to question.title, field_question_path(id:question.url, field_id:Field.find(question.field_id).name), class: "no-formatt blue-link" %>":
			<div class="notification-preview">
			  "<%= answer.content %>"
			</div>
			on <%= answer.created_at %>
		<% elsif notification.desc=="new_reply"%>
			<% reply = Reply.find(notification.model_id) %>
			<% post = Post.find(reply.post_id) %>
			You have a new reply for the post,"<%= link_to post.title[0..15]+"...", topic_post_path(id: post.url, topic_id: Topic.find(post.topic_id).url) , class: "no-formatt blue-link" %>":
			<div class="notification-preview">
			  "<%= reply.content %>"
			</div>
			on <%= reply.created_at %>
		<% elsif notification.desc=="best_answer" %>
			<% answer = Answer.find(notification.model_id) %>
			<% question = Question.find(answer.question_id) %>
			Congradulations! Your answer:
			<div class="notification-preview">
			  "<%= answer.content %>"
			</div>
			to "<%= link_to question.title, field_question_path(id:question.url, field_id:Field.find(question.field_id).name), class: "no-formatt blue-link" %>" has been chosen as the <strong>best answer</strong>, on <%= answer.updated_at %>.
		<% end %>
	  </div>
	  <%= link_to "dismiss", notification, method: :delete, class: "no-formatt not-important float-right" %>
	</div>
<% end %>
<% @seen_notifications.each  do |notification|%>
	<div class="notification seen">

	  <div class="notification-content">
		<% if notification.desc=="new_answer"%>
			<% answer = Answer.find(notification.model_id) %>
			<% user = User.find(answer.user_id) %>
			<% question = Question.find(answer.question_id) %>
			<%= link_to user.name, user_path(user.name, class: "no-formatt blue-link") %> has answered your question "<%= link_to question.title, field_question_path(id:question.url, field_id:Field.find(question.field_id).name), class: "no-formatt blue-link" %>":
			<div class="notification-preview">
			  "<%= answer.content %>"
			</div>
			on <%= answer.created_at %>
		<% elsif notification.desc=="new_reply"%>
			<% reply = Reply.find(notification.model_id) %>
			<% post = Post.find(reply.post_id) %>
			You have a new reply for the post,"<%= link_to post.title[0..15]+"...", topic_post_path(id: post.url, topic_id: Topic.find(post.topic_id).url) , class: "no-formatt blue-link" %>":
			<div class="notification-preview">
			  "<%= reply.content %>"
			</div>
			on <%= reply.created_at %>
		<% elsif notification.desc=="best_answer" %>
			<% answer = Answer.find(notification.model_id) %>
			<% question = Question.find(answer.question_id) %>
			Congradulations! Your answer:
			<div class="notification-preview">
			  "<%= answer.content %>"
			</div>
			to "<%= link_to question.title, field_question_path(id:question.url, field_id:Field.find(question.field_id).name), class: "no-formatt blue-link" %>" has been chosen as the <strong>best answer</strong>, on <%= answer.updated_at %>.
		<% end %>
	  </div>
	  <%= link_to(image_tag( image_url('delete.png'), class: "delete-image"),notification,  method: :delete, class: "no-formatt not-important float-right")%>
	</div>
<% end %>